files = [
    "C:\Users\kuzga\Downloads\1 (11).pdf"
    "C:\Users\kuzga\Downloads\1 (10).pdf"
    "C:\Users\kuzga\Downloads\1 (9).pdf"
    "C:\Users\kuzga\Downloads\1 (8).pdf"
    "C:\Users\kuzga\Downloads\1 (7).pdf"
    "C:\Users\kuzga\Downloads\1 (6).pdf"
    "C:\Users\kuzga\Downloads\1 (5).pdf"
    "C:\Users\kuzga\Downloads\1 (4).pdf"
    "C:\Users\kuzga\Downloads\1 (3).pdf"
    "C:\Users\kuzga\Downloads\1 (2).pdf"
    "C:\Users\kuzga\Downloads\1 (1).pdf"
    "C:\Users\kuzga\Downloads\1.pdf"
    "C:\Users\kuzga\Downloads\1 (17).pdf"
    "C:\Users\kuzga\Downloads\1 (16).pdf"
    "C:\Users\kuzga\Downloads\1 (15).pdf"
    "C:\Users\kuzga\Downloads\1 (14).pdf"
    "C:\Users\kuzga\Downloads\1 (13).pdf"
    "C:\Users\kuzga\Downloads\1 (12).pdf"
]